### ISSUE TITLE
Create a PWA app that brings a big digital clock to your wall using Augmented Reality 

### ISSUE THREAD

**Issue by rahul101001000** [donew-innovations/moonshot-ideas#10]
#### Context
ARjs or MindAR are libraries for creating AR experiences for the web. 

#### Project
Create a big digital virtual clock that shows up on a vertical surface (wall) when you view the world from your front camera. 

#### Milestones
- [ ] Ramp up on [ARjs](https://ar-js-org.github.io/AR.js-Docs/), create a sample app 
- [ ] For a more advanced overview, take [this course](https://www.udemy.com/course/introduction-to-web-ar-development/?referralCode=D2565F4CA6D767F30D61)
- [ ] Detect vertical surfaces
- [ ] Create virtual digital clock and place it on the vertical surface
- [ ] Package as a PWA and list on Android playstore and also allow link to the AR experience be shared via Whatsapp
