### ISSUE TITLE
Evaluation of global Central Bank Digital Currency (CBDC) implementations

### ISSUE THREAD

**Issue by rahul101001000** [donew-innovations/moonshot-ideas#6]
#### Context
[CDBCs](https://en.wikipedia.org/wiki/Central_bank_digital_currency) are being [implemented across the globe](https://cbdctracker.org/). Some of the implementations include - 
- MIT's OpenCBDC [documentation](https://dci.mit.edu/opencbdc) and [Github code](https://github.com/mit-dci/opencbdc-tx)
- A [Daml open smart contracting](https://www.digitalasset.com/developers) based demo implementation created for OECD is available on [Github here](https://github.com/digital-asset/ex-cbdc/blob/main/CBDC_Demo_User_Guide.pdf). 
- [RBI's concept note ](https://rbidocs.rbi.org.in/rdocs/PublicationReport/Pdfs/CONCEPTNOTEACB531172E0B4DFC9A6E506C2C24FFB6.PDF) on CBDC for India 
- [iSPIRT's Bharat Distributed Ledger BADAL](https://pn.ispirt.in/badal-for-accelerating-commerce-in-india/) concept 
- iSPIRT's Public Private Ledger (PPL) [implementation on Github](https://github.com/iSPIRT/ppl/blob/master/docs/ppl-info-architecture.md). 

#### Project
Install and run all the above implementations of CBDC prototypes. Figure out parameters for evaluation based on RBI concept note above. Write a paper comparing different approaches and which one is closest to the requirements in the RBI concept note. 

#### Milestones
- [ ] Install and run all the above implementations of CBDC prototypes. 
- [ ] Figure out parameters for evaluation based on RBI concept note above. 
- [ ] Write a paper comparing different approaches and which one is closest to the requirements in the RBI concept note.
