### ISSUE TITLE
Prayers in the Metaverse with Augmented Reality (AR)

### ISSUE THREAD

**Issue by rahul101001000** [donew-innovations/moonshot-ideas#7]
#### Context
360 videos exist for [temples](https://www.youtube.com/watch?v=6-DgkPCKxGo). These can be viewed on Youtube, using a phone, or using Google Cardboard or Oculus Quest. Since these devices has a front camera, one can even experience augmented reality (AR) (your current real world superimposed with the virtual world). Unity is the preferred platform to create VR and AR experiences and is available at no cost for non commercial use on the [Unity download page](https://unity.com/download). 

#### Project
Can you create an AR experience to allow a devotee to offer prayers at a temple? This may include superimposing candle/puja thali from the real world onto the virtual world, placing the puja thali on a table in the real world and see that placed on a similar platform in the temple. 

#### Milestones
- [ ] Set up Unity for Android using [this tutorial](https://www.youtube.com/watch?v=0mpsiO2lCx0).
- [ ] Learn plane detection in Unity using [this tutorial](https://www.youtube.com/watch?v=uWWiYfPTUtU) 
- [ ] Learn to place objects in Unity using [this tutorial](https://www.youtube.com/watch?v=xguiSueY1Lw)
- [ ] Figure out how to import temple 360 video into Unity
- [ ] Use your creative magic and create a prayer experience
