### ISSUE TITLE
Google Sheets and App script based student management for coaching institute

### ISSUE THREAD

**Issue by rahul101001000** [donew-innovations/moonshot-ideas#8]
#### Context
Tuition teachers, coaching institutes, NGOs in the education space need to manage list of students enrolled, track collection of fees, track student and teacher attendance in classes among other things. Several commercial software options are available to do the same such as [SchoolonApp](https://schoolonapp.com/schoolonapp-plans), [Fekara](https://fekara.com/pricing-plans/), [Classe365](https://www.classe365.com/pricing/), [Fedena](
https://fedena.com/pricing-and-plans), [MyClassCampus](
https://myclasscampus.com/plans) amongst others. 

Small organizations who cannot afford these tools often rely on spreadsheets to do the same, albeit with manual intervention. Google Sheets, Google Forms and App script for custom programs are a powerful combination to achieve similar functionality. 

#### Project
Create a Google Sheets, Forms and Apps Script based open source product that can help small organizations manage the end to end student lifecycle. 

#### Milestones
- [ ] Define steps in the workflow for students and teachers
- [ ] Create schemas for teacher, student, fee payments, etc and store all data in different tabs in Google Sheets 
- [ ] Use Google Forms to get data from teachers/students
- [ ] Use Apps Script to populate Google Forms drop down with data from spreadsheet. See [tutorial](https://www.youtube.com/watch?v=o3AL7ASI_cA) for this
- [ ] Prefill data in Google Forms using [this tutorial](https://www.youtube.com/watch?v=xk7R3Z_fSCI).
- [ ] Add more functionality to get this to at least 70% of commercial products listed above
- [ ] Package it as a Google Sheet Add on and list it on the Apps marketplace.
