### ISSUE TITLE
Create big digital clock for Android

### ISSUE THREAD

**Issue by rahul101001000** [donew-innovations/moonshot-ideas#9]
#### Context
[Huge Digital Clock](https://play.google.com/store/apps/details?id=com.cama.app.huge80sclock&gl=US) is a popular digital clock on the Android playstore. However it often gets flagged as malware in virus scans, is not open source and is only available as an app, not as a web site / PWA.

#### Project
Create a distraction free, full screen digital clock with hours/min/seconds, option to turn off seconds, available in multiple fonts and colors, ability to adjust to portrait/landscape mode changes easily. Create this as a PWA app. 

#### Milestones
- [ ] Define feature list of what you want to implement
- [ ] Create your first PWA app using [this tutorial](https://www.youtube.com/watch?v=WbbAPfDVqfY)
- [ ] Add functionality for clock to get it working in landscape mode
- [ ] Add responsive design to allow it to operate across phone sizes and in landscape or portrait mode
- [ ] Add functionality to change font/style
- [ ] Launch it as a PWA app on Android Playstore
